<?php

namespace AppBundle\Repository;

/**
 * CharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *
     * @return array
     */
    public function getAllCharacters()
    {
        $entityManager = $this->getEntityManager();
        $queryBuilder = $entityManager->createQueryBuilder();
        $queryBuilder
            ->select('ch')
            ->from('AppBundle:Character', 'ch');

        return $queryBuilder->getQuery()->getResult();
    }
}
